#!/usr/bin/env bash
#
# setup.sh — bootstrap for the niri desktop dotfiles
# Target: Arch Linux (base install per the Kiln guide linked in the
# README), fresh or existing.
#
# The repository layout is the source of truth:
#   config/   mirrors ~/.config and is symlinked there, entry by entry —
#             edits in the repo are live (niri and starship reload on
#             save; the shell's config/bash/ on the next shell).
#             config/systemd/user holds the session's units and
#             config/environment.d the toolkits' environment, both read
#             by the systemd user manager
#   bin/      mirrors ~/.local/bin, symlinked the same way; the login
#             shell's profile (config/bash/profile) puts ~/.local/bin on
#             PATH and niri-session imports that environment, so binds
#             name these bare (units spell the path: they depend on
#             nothing a login shell did or did not set)
#   system/   mirrors / and is installed there, file by file (root-owned
#             copies, not links): the boot chain (GRUB and mkinitcpio
#             drop-ins, plymouth and its theme, the plymouth-quit
#             hand-off) and the login page (greetd, the greeter niri,
#             monogreet) — what the desktop needs below the user
#   templates/ mirrors ~/Templates (the XDG templates dir), copied file
#             by file: what Files offers under "New Document"
#   icons/    icon themes, each linked into ~/.local/share/icons: mono,
#             Adwaita's folders and files redrawn on the palette
#             (generated by tools/mono-icons, committed)
#   tools/    generators for committed assets (the plymouth theme's
#             images) and the ring screens' live test; not installed
#             anywhere
#   setup.sh  everything a config file cannot express: packages, system
#             glue (units, the initramfs and grub.cfg rebuilds, the
#             greeter's state dirs and background, MIME defaults,
#             gsettings, the ~/.bashrc hook, the btop setting), the
#             linking itself, session reloads, and the final summary
#
# Everything installs from the official repositories — the workspace
# alone, no end-user applications (browsers, VPN, messengers, media
# apps are installed by hand afterwards). paru is bootstrapped as the
# tool for those later AUR installs, and the bar's updates module
# upgrades through it, but this script installs nothing from the AUR.
# No other third-party builds, and one release-binary download: herdr,
# the agent workspace manager, through its official installer (2b).
# Changes to the session environment (config/bash/profile,
# config/environment.d) reach a running session on the next login; a
# run says so.
#
# A real file or directory found where a link belongs is moved aside once
# as <name>.pre-dotfiles. Version history lives in git log.
#
# Usage:  bash setup.sh          full run: install everything + link configs
#         bash setup.sh link     (re)link configs + validate + reload only
#         bash setup.sh system   packages + the system/ tree + boot and
#                                greeter glue only (sudo; the user half
#                                untouched)
#         bash setup.sh summary  print the probed component summary
#
set -euo pipefail

# ---------------------------------------------------------------- helpers ---
log()  { printf '\033[1m[setup]\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m[setup] WARNING:\033[0m %s\n' "$*" >&2; }
die()  { printf '\033[1;31m[setup] ERROR:\033[0m %s\n' "$*" >&2; exit 1; }
have() { command -v "$1" >/dev/null 2>&1; }

[ "$(id -u)" -eq 0 ] && die "run as your user, not root (sudo is used where needed)"

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CFG="$HOME/.config"
MONO_FONT="JetBrainsMono Nerd Font"

WORK="$(mktemp -d -t dotfiles-setup.XXXXXX)"
trap 'rm -rf "$WORK"' EXIT

# Match the full family name: a vanilla "JetBrains Mono" install also greps
# true for bare "JetBrainsMono" and would skip the Nerd Font glyphs.
font_ok() { fc-match "$MONO_FONT" | grep -q "JetBrainsMono Nerd Font"; }

# ------------------------------------------------------------- 1. packages ---
# One transaction, official repos only. --needed keeps reruns cheap and
# never reinstalls; the full-system upgrade first is the supported way to
# install on Arch (partial upgrades are not). noto-fonts and
# noto-fonts-emoji stand behind JetBrains Mono for the scripts and emoji
# it lacks — without a fallback those render as hex boxes (in
# notifications first: chat apps).
install_packages() {
    log "pacman packages"
    sudo pacman -Syu --needed --noconfirm \
        niri xwayland-satellite \
        alacritty waybar mako swaybg swayidle hyprlock rofi \
        yazi zellij cliphist starship chafa micro btop \
        zathura zathura-pdf-poppler imv mpv \
        tlp \
        grim slurp ksnip imagemagick brightnessctl pulsemixer wtype \
        fzf zoxide wl-clipboard fd ripgrep eza bat git-delta jq \
        p7zip unzip xdg-user-dirs \
        libnotify gcr-4 qt5-wayland \
        gsettings-desktop-schemas adwaita-icon-theme \
        xdg-desktop-portal xdg-desktop-portal-gtk xdg-desktop-portal-gnome \
        pipewire pipewire-pulse pipewire-alsa wireplumber \
        plymouth greetd python-gobject gtk4 \
        ttf-jetbrains-mono-nerd noto-fonts noto-fonts-emoji pacman-contrib

    [ -f /usr/share/wayland-sessions/niri.desktop ] \
        || die "niri.desktop missing from wayland-sessions — session not registered"
    font_ok || die "ttf-jetbrains-mono-nerd installed but fc-match does not resolve it"
    log "font ok: $(fc-match "$MONO_FONT")"

    # X11 apps (Steam, Discord, ...): niri >= 25.08 spawns xwayland-satellite
    # on demand, exports $DISPLAY, and restarts it if it dies — the binary in
    # $PATH is the whole requirement. No spawn-at-startup, no env plumbing.
}

# ------------------------------------------------------------------ 2. AUR ---
# paru is the tool, not a package source: this script installs nothing
# from the AUR. It is bootstrapped so the bar's updates module can
# upgrade repos and AUR alike (`paru -Syu`, plain pacman before paru
# exists) and so applications chosen later (a browser, a VPN, music)
# install by hand with `paru -S <pkg>`. paru-bin skips the Rust
# compile, but its prebuilt binary hard-links a libalpm soname and
# lags pacman's soname bumps (broken against pacman >= 7.1 when this
# was written) — a binary that exists but cannot load looks installed
# to `command -v`. So the probe is `paru --version` actually running,
# and the fallback builds the paru source package, which links
# whatever libalpm the system really has.
paru_ok() { paru --version >/dev/null 2>&1; }

aur_build() {
    git clone -q "https://aur.archlinux.org/$1.git" "$WORK/$1"
    # -s pulls makedeps from the repos (cargo/rust for the source paru;
    # rust stays installed — paru's own self-updates recompile with it)
    (cd "$WORK/$1" && makepkg -si --noconfirm)
}

install_paru() {
    paru_ok && return 0
    log "bootstrapping paru (AUR helper)"
    # makepkg needs the base-devel group; --needed makes this free
    # on systems that already carry it
    sudo pacman -S --needed --noconfirm base-devel
    if have paru; then
        # present but not runnable: a stale prebuilt against an older
        # libalpm — drop whichever package owns it before rebuilding
        warn "installed paru does not run — replacing with source build"
        sudo pacman -R --noconfirm "$(pacman -Qoq "$(command -v paru)")"
    else
        aur_build paru-bin
        paru_ok && return 0
        warn "paru-bin links an older libalpm — building paru from source"
        sudo pacman -R --noconfirm paru-bin
    fi
    aur_build paru
    paru_ok || die "paru bootstrap failed"
}

# --------------------------------------------------------------- 2b. herdr ---
# herdr (herdr.dev) — terminal workspace manager for coding agents,
# alongside zellij. It is the one release-binary download here: no repo
# package, and the AUR herdr-bin would land in /usr/bin where herdr's
# own updater (`herdr update`) cannot write and refuses to run. The
# official installer fetches the release manifest, verifies the asset's
# SHA-256, and drops the static binary in ~/.local/bin (on PATH through
# config/bash/profile). From then on `herdr update` keeps it current, so
# an existing binary is left alone — this step is install-once.
HERDR_INSTALLER="https://herdr.dev/install.sh"

install_herdr() {
    have herdr && return 0
    log "installing herdr (agent workspace manager) into ~/.local/bin"
    mkdir -p "$HOME/.local/bin"
    # fetched to a file first: a truncated download must not run half a script
    curl -fsSL --retry 3 --connect-timeout 10 --max-time 30 \
        "$HERDR_INSTALLER" -o "$WORK/herdr-install.sh" \
        || die "can't fetch $HERDR_INSTALLER"
    HERDR_INSTALL_DIR="$HOME/.local/bin" sh "$WORK/herdr-install.sh"
    [ -x "$HOME/.local/bin/herdr" ] || die "herdr install failed"
}

# --------------------------------------------------------- 3. system units ---
# paccache: bound the pacman cache (the @pkg subvolume is excluded from
# snapshots but nothing else limits it). tlp: battery-side runtime power
# tuning, stock defaults (machines that expose a charge-threshold
# interface can set thresholds in /etc/tlp.conf; nothing else needs
# configuring).
enable_system_units() {
    sudo systemctl enable paccache.timer 2>/dev/null \
        || warn "could not enable paccache.timer"
    sudo systemctl enable tlp 2>/dev/null \
        || warn "could not enable tlp"
}

# ---------------------------------------------------------- 4. system tree ---
# system/ mirrors /: every file under it is installed to the same path,
# root-owned, the way config/ mirrors ~/.config — one tree, one rule;
# a file executable in the repo (monogreet) is executable in place.
# Files already identical in place are left alone, so a rerun is quiet;
# the paths that did change are collected for the stages below, which
# rebuild only what those files feed (the initramfs, grub.cfg).
#
# A directory the repo fills wholly is mirrored exactly: a file in it
# that the repo no longer ships is removed. The plymouth theme dir is
# the case that matters — the theme and its images travel together
# into the initramfs, and a redesign that drops an image (or, once, the
# whole two-step image set) must take it off the disk too, or the
# stale file is packed along. /etc/greetd and the drop-in dirs also carry files the packages
# own; only named leftovers of this repo's own past (SYSTEM_RETIRED)
# are removed there.
SYSTEM_CHANGED=()
SYSTEM_MIRRORED_DIRS=(/usr/share/plymouth/themes/mono)
SYSTEM_RETIRED=(/etc/greetd/regreet.css)   # the regreet page's stylesheet

install_system_files() {
    local src dest mode dir file
    while IFS= read -r -d '' src; do
        dest="${src#"$REPO/system"}"
        cmp -s "$src" "$dest" && continue
        mode=644
        [ -x "$src" ] && mode=755
        log "installing $dest"
        sudo install -D -m "$mode" "$src" "$dest"
        SYSTEM_CHANGED+=("$dest")
    done < <(find "$REPO/system" -type f -print0 | sort -z)
    for dir in "${SYSTEM_MIRRORED_DIRS[@]}"; do
        [ -d "$dir" ] || continue
        while IFS= read -r -d '' file; do
            [ -e "$REPO/system$file" ] && continue
            log "removing $file (no longer in the repo)"
            sudo rm -f "$file"
            SYSTEM_CHANGED+=("$file")
        done < <(find "$dir" -type f -print0 | sort -z)
    done
    for file in "${SYSTEM_RETIRED[@]}"; do
        [ -e "$file" ] || continue
        log "removing retired $file"
        sudo rm -f "$file"
        SYSTEM_CHANGED+=("$file")
    done
}

system_changed_under() {
    local path
    for path in "${SYSTEM_CHANGED[@]}"; do
        [[ $path == "$1"* ]] && return 0
    done
    return 1
}

# ----------------------------------------------------------------- 5. boot ---
# The boot chain is plymouth from the initramfs to the greeter: the
# mkinitcpio drop-in puts the hook in, plymouthd.conf names the theme,
# the GRUB drop-in hides the menu and adds `splash`. Those files only
# take effect inside the images they feed, so the initramfs is rebuilt
# when anything plymouth or mkinitcpio changed (the theme and its font
# are packed into it) and grub.cfg when the GRUB drop-in did. A fresh
# plymouth install is caught the same way: its drop-in is new then.
# Should a splash ever misbehave, `plymouth.enable=0` on the kernel
# line (Esc at boot, e on the entry) boots with the text prompt.
configure_boot() {
    if system_changed_under /etc/mkinitcpio.conf.d \
        || system_changed_under /etc/plymouth \
        || system_changed_under /usr/share/plymouth; then
        log "rebuilding the initramfs (plymouth + theme)"
        sudo mkinitcpio -P
    fi
    if system_changed_under /etc/default/grub.d; then
        log "regenerating grub.cfg"
        sudo grub-mkconfig -o /boot/grub/grub.cfg
    fi
    # the plymouth-quit drop-in is read at the next boot; reload so a
    # `systemctl cat` shows it now
    if system_changed_under /etc/systemd/system; then
        sudo systemctl daemon-reload
    fi
}

# -------------------------------------------------------------- 6. greeter ---
# greetd runs the greeter niri (system/etc/greetd/niri.kdl), which runs
# monogreet (system/usr/local/bin). monogreet keeps the last user and
# session under /var/lib/monogreet, owned by the greeter user the greetd
# package creates. Its background is the wallpaper as the lock screen's
# glass — bin/glass renders what hyprlock draws live — made here because
# only setup runs with the privilege to place it; it is remade whenever
# the wallpaper or bin/glass is newer than the copy. Enable only writes
# symlinks — greetd takes the VT at the next boot, never mid-session.
configure_greeter() {
    sudo install -d -o greeter -g greeter -m 0755 /var/lib/monogreet
    local wall="$HOME/Pictures/wallpaper.jpg" bg=/usr/share/backgrounds/greeter.jpg
    if [ -f "$wall" ] && have magick; then
        if [ ! -f "$bg" ] || [ "$wall" -nt "$bg" ] || [ "$REPO/bin/glass" -nt "$bg" ]; then
            log "rendering the login page background from the wallpaper"
            "$REPO/bin/glass" "$wall" "$WORK/greeter.jpg"
            sudo install -Dm644 "$WORK/greeter.jpg" "$bg"
        fi
    fi
    sudo systemctl enable greetd 2>/dev/null \
        || warn "could not enable greetd"
}

# ---------------------------------------------------- 7. MIME associations ---
# xdg-mime records an association even for a desktop file that does not
# exist, silently breaking xdg-open; only associate what is actually shipped.
set_mime_default() {
    local desk="$1"; shift
    if [ -f "/usr/share/applications/$desk" ]; then
        xdg-mime default "$desk" "$@"
    else
        warn "$desk not installed; MIME defaults for $* left unchanged"
    fi
}

set_default_apps() {
    log "MIME defaults (zathura for PDFs, imv for images)"
    set_mime_default org.pwmt.zathura.desktop application/pdf

    # the imv package's desktop file name has varied; pick the one shipped
    local d imv_desk=""
    for d in imv-dir.desktop imv.desktop; do
        if [ -f "/usr/share/applications/$d" ]; then imv_desk="$d"; break; fi
    done
    if [ -n "$imv_desk" ]; then
        xdg-mime default "$imv_desk" image/png image/jpeg image/webp image/gif
    else
        warn "no imv desktop file found; image MIME defaults left unchanged"
    fi
}

# ------------------------------------------------------------- 7b. git ---
# The workspace's git settings are config/git/config (linked with the
# rest). Identity and anything machine-bound go in ~/.gitconfig, which
# git reads alongside it — and `git config --global` writes to
# ~/.gitconfig only if it exists; absent, the XDG file would be the
# target, and a name, an email or a credential helper would land in a
# tracked file. So the identity file exists before anything asks.
configure_git() {
    [ -f "$HOME/.gitconfig" ] || touch "$HOME/.gitconfig"
}

# ------------------------------------------------------------ 8. link tree ---
# Symlink each top-level entry of config/ into ~/.config, each file in
# bin/ into ~/.local/bin and each theme in icons/ into ~/.local/share/icons.
# Directory-level links keep the mapping obvious: one entry in the repo,
# one link on disk. A real file or directory already in the way is moved
# aside once as <name>.pre-dotfiles.
#
# Two programs write live state beside their configuration, so their
# dirs are not linked whole — a whole-dir link would point those writes
# into the repo: btop rewrites btop.conf on every exit (configure_btop
# links its read-only themes/ and enforces the intent lines in place),
# micro keeps buffers/ (configure_micro links the configuration files
# only).
PARTIALLY_LINKED=(btop micro)

link_one() {
    local src="$1" dest="$2"
    if [ -L "$dest" ] && [ "$(readlink -f "$dest")" = "$src" ]; then
        return 0
    fi
    if [ -e "$dest" ] && [ ! -L "$dest" ]; then
        mv "$dest" "$dest.pre-dotfiles"
        log "moved existing $dest aside as $dest.pre-dotfiles"
    else
        rm -f "$dest"
    fi
    ln -s "$src" "$dest"
    log "linked $dest"
}

link_configs() {
    local src link name
    mkdir -p "$CFG" "$HOME/.local/bin"
    for src in "$REPO/config"/*; do
        name="$(basename "$src")"
        [[ " ${PARTIALLY_LINKED[*]} " == *" $name "* ]] && continue
        link_one "$src" "$CFG/$name"
    done
    for src in "$REPO/bin"/*; do
        link_one "$src" "$HOME/.local/bin/$(basename "$src")"
    done
    mkdir -p "$HOME/.local/share/icons"
    for src in "$REPO/icons"/*; do
        link_one "$src" "$HOME/.local/share/icons/$(basename "$src")"
    done
    # prune links left behind by entries removed from the repo
    for link in "$CFG"/* "$HOME/.local/bin"/* "$HOME/.local/share/icons"/*; do
        if [ -L "$link" ] && [[ "$(readlink "$link")" == "$REPO"/* ]] && [ ! -e "$link" ]; then
            rm "$link"
            log "pruned stale link $link"
        fi
    done
}

# Files builds its "New Document" menu from the XDG templates dir, one
# entry per file there, named without its extension, and creates a copy
# of the file; an empty ~/Templates (what xdg-user-dirs leaves) means no
# entry at all and a file manager that seemingly cannot create files.
# templates/ is copied, not linked: Files copies the template as-is, so
# a symlink template would hand out a link. A .sh keeps its mode.
install_templates() {
    local dir src dest mode
    # xdg-user-dir answers $HOME for a dir that is unset or disabled
    dir="$(xdg-user-dir TEMPLATES 2>/dev/null || true)"
    if [ -z "$dir" ] || [ "$dir" = "$HOME" ]; then
        dir="$HOME/Templates"
    fi
    mkdir -p "$dir"
    for src in "$REPO/templates"/*; do
        [ -f "$src" ] || continue
        dest="$dir/$(basename "$src")"
        mode=644
        [ -x "$src" ] && mode=755
        if cmp -s "$src" "$dest" \
            && [ "$(stat -c %a "$dest")" = "$mode" ]; then
            continue
        fi
        install -m "$mode" "$src" "$dest"
        log "installed template $dest"
    done
}

# The session runs on systemd user units: the packages' waybar.service
# and mako.service, and the repo's (config/systemd/user — linked into
# place by link_configs like any other entry) for the wallpaper, idle
# management, clipboard history and the battery watch. All are bound to
# graphical-session.target, which niri.service reaches once the
# compositor is up, so they start with the session, stop with it, and
# restart, reload and log like any unit. Enabling them is the glue only
# setup can do; `enable` writes the wants links whether or not a session
# is up, and reload_session starts them in a live one.
# Outside the session: waybar-updates.path pokes the bar's updates
# module whenever the pacman database changes; gcr-4 ships the ssh
# agent (gnome-keyring, which once carried it, is not part of this
# desktop) — its socket unit exports SSH_AUTH_SOCK into the session.
SESSION_UNITS=(waybar.service mako.service wallpaper.service swayidle.service
               battwatch.service cliphist@text.service cliphist@image.service)

enable_units() {
    local out
    systemctl --user daemon-reload 2>/dev/null || true
    out="$(systemctl --user enable "${SESSION_UNITS[@]}" waybar-updates.path gcr-ssh-agent.socket 2>&1)" \
        || warn "could not enable the user units: $out"
    systemctl --user start waybar-updates.path gcr-ssh-agent.socket 2>/dev/null || true
}

# ---------------------------------------------------------- 9. shell setup ---
# The shell's configuration is config/bash/ — profile for login shells
# (PATH, EDITOR: the environment niri-session imports for the whole
# session), bashrc for interactive ones — linked with the rest of
# config/ and live on edit. ~/.bash_profile and ~/.bashrc stay the
# system's own files and each carries one line of this repo's, sourcing
# its file (bash reads no XDG path of its own). Earlier versions wrote
# the configuration into ~/.bashrc as a marked block — that block is
# removed once, its content is the linked file now.
install_shell_hook() {   # install_shell_hook RCFILE NAME — hook config/bash/NAME into ~/RCFILE
    local rc="$HOME/$1" name="$2"
    local hook="[ -r ~/.config/bash/$name ] && . ~/.config/bash/$name"
    [ -f "$rc" ] || touch "$rc"
    if grep -q '^# >>> dotfiles managed block >>>$' "$rc"; then
        log "removing the managed block from ~/$1 (config/bash/ carries it now)"
        awk '/^# >>> dotfiles managed block >>>$/,/^# <<< dotfiles managed block <<<$/ { next }
             { print }' "$rc" > "$WORK/rc"
        cat "$WORK/rc" > "$rc"
    fi
    grep -qxF "$hook" "$rc" && return 0
    log "hooking config/bash/$name into ~/$1"
    printf '\n# the shell configuration of ~/dotfiles (config/bash/%s)\n%s\n' "$name" "$hook" >> "$rc"
}

install_shell_hooks() {
    # bash reads the first of ~/.bash_profile and ~/.profile at login: a
    # machine that has only ~/.profile keeps it (creating ~/.bash_profile
    # beside it would silence it)
    if [ ! -f "$HOME/.bash_profile" ] && [ -f "$HOME/.profile" ]; then
        install_shell_hook .profile profile
    else
        install_shell_hook .bash_profile profile
    fi
    install_shell_hook .bashrc bashrc
}

# btop rewrites its whole config file on every clean exit, so linking it
# would put btop's runtime state under git. Like ~/.bashrc it stays a
# real file owned by the program; only the intended settings are
# enforced in place: theme_background False lets the terminal's glass
# show through instead of btop painting an opaque ground. The themes
# dir is read-only to btop and links normally (excluded from
# link_configs, owned here).
btop_set() {
    local conf="$CFG/btop/btop.conf" key="$1" value="$2"
    if grep -qs "^$key\b" "$conf"; then
        sed -i "s|^$key\b.*|$key = $value|" "$conf"
    else
        printf '%s = %s\n' "$key" "$value" >> "$conf"
    fi
}

configure_btop() {
    mkdir -p "$CFG/btop"
    link_one "$REPO/config/btop/themes" "$CFG/btop/themes"
    btop_set theme_background False
    btop_set color_theme '"mono"'
    btop_set vim_keys True
}

# micro's config dir carries live state (buffers/) next to the real
# configuration, so only the configuration links into the repo. The
# settings.json symlink is safe and deliberate: micro rewrites the file
# through the link on every exit in a stable normal form (alphabetical
# keys, 4-space indent) — the committed file is kept in that form, so
# the routine rewrite is byte-identical and the repo stays clean, while
# an interactive `set` lands in the repo as a visible diff to commit or
# revert (all verified on micro 2.0.13).
configure_micro() {
    mkdir -p "$CFG/micro"
    link_one "$REPO/config/micro/settings.json" "$CFG/micro/settings.json"
    link_one "$REPO/config/micro/colorschemes" "$CFG/micro/colorschemes"
}

# ------------------------------------------------------------- 10. desktop ---
apply_desktop_prefs() {
    # the desktop is dark throughout (the 0d0d0d ground of every surface),
    # and the settings portal hands this preference to every toolkit —
    # libadwaita picks its dark stylesheet (config/gtk-4.0/gtk.css
    # recolours it onto the palette either way), browsers, Qt and
    # Electron apps follow suit
    gsettings set org.gnome.desktop.interface color-scheme prefer-dark 2>/dev/null || true
    gsettings set org.gnome.desktop.interface gtk-theme Adwaita 2>/dev/null || true
    # GTK apps follow the one-typeface rule and the compositor's cursor
    # choice (cursor block in config/niri/input.kdl).
    gsettings set org.gnome.desktop.interface font-name "'$MONO_FONT 10'" 2>/dev/null || true
    gsettings set org.gnome.desktop.interface monospace-font-name "'$MONO_FONT 11'" 2>/dev/null || true
    gsettings set org.gnome.desktop.interface cursor-theme "'Adwaita'" 2>/dev/null || true
    gsettings set org.gnome.desktop.interface cursor-size 24 2>/dev/null || true
    # icons/mono: Adwaita, with its folders and files on the palette
    gsettings set org.gnome.desktop.interface icon-theme "'mono'" 2>/dev/null || true
    # Files (nautilus): its colours and glass come from
    # config/gtk-4.0/gtk.css (linked with the rest of config/). The view
    # itself — grid or list — is not set here: Files' own toggle writes
    # default-folder-viewer, and a run of this script must not undo a
    # choice made in the window. Only the shape of each view is fixed:
    # a compact list of name, size and date; no captions under icons.
    gsettings set org.gnome.nautilus.list-view default-zoom-level "'small'" 2>/dev/null || true
    gsettings set org.gnome.nautilus.list-view default-visible-columns \
        "['name', 'size', 'date_modified']" 2>/dev/null || true
    gsettings set org.gnome.nautilus.icon-view captions "['none', 'none', 'none']" 2>/dev/null || true
    # Files' sidebar: Desktop and Downloads pinned under the fixed
    # places. Bookmarks live in the GTK bookmarks file (GTK 4 still
    # reads the gtk-3.0 path). Ensured line by line rather than written
    # whole, so a folder pinned from the window survives a rerun.
    local bm="$CFG/gtk-3.0/bookmarks" dir
    mkdir -p "$CFG/gtk-3.0"
    touch "$bm"
    for dir in Desktop Downloads; do
        grep -qxF "file://$HOME/$dir" "$bm" || printf 'file://%s/%s\n' "$HOME" "$dir" >> "$bm"
    done
}

# -------------------------------------------------------------- 11. reload ---
# niri reloads its own config on save and starship re-reads per prompt;
# the daemons are units. The ones that hold config in memory — a git
# pull can change their files without any link changing — are reloaded
# where the unit can (mako) and restarted where it cannot (a restart is
# a fresh process; a reload signal sent to a bar that has only just
# started would reach it before its handler is in place); then whatever
# is not up yet is started — a no-op for the running ones. The user
# manager carries the session's environment, so this works from an ssh
# shell too; with no session up there is nothing to do.
reload_session() {
    systemctl --user -q is-active graphical-session.target 2>/dev/null || return 0
    stop_legacy_daemons
    log "restarting the session units"
    systemctl --user restart waybar.service swayidle.service 2>/dev/null \
        || warn "a session unit did not restart — journalctl --user -u waybar -u swayidle"
    systemctl --user reload-or-restart mako.service 2>/dev/null \
        || warn "mako did not reload — journalctl --user -u mako"
    systemctl --user start "${SESSION_UNITS[@]}" 2>/dev/null \
        || warn "a session unit did not start — systemctl --user status ${SESSION_UNITS[*]}"
    session_env_current \
        || warn "this session started before config/bash/profile reached it: the binds that name a bin/ script bare (launcher, lock, power and network menus, clipboard, annotate) find nothing until the next login — log out and in"
}

# A session that began under the previous design still runs the daemons
# as niri's children: spawn-at-startup put each in an app-niri-<argv0>-
# <pid>.scope — sh for the three wrapper scripts (the bar, the wallpaper,
# the battery watch), mako, swayidle, wl-paste. A config reload does not
# end them, and beside the units they would be a second bar, a second
# wallpaper, and a mako holding the notification name the unit needs.
# Each such scope is stopped once, before the units take over: the
# daemon's name and a legacy scope name together pick them out, so a
# terminal scope that merely contains a swaybg run by hand is left alone.
stop_legacy_daemons() {
    local pid cgroup scopes=()
    for pid in $(pgrep -u "$(id -u)" -x 'waybar|mako|swaybg|swayidle|wl-paste|battwatch.sh'); do
        cgroup="$(cut -d: -f3 "/proc/$pid/cgroup" 2>/dev/null)"
        if [[ $cgroup =~ /(app-niri-(sh|mako|swayidle|wl\\x2dpaste)-[0-9]+\.scope)$ ]]; then
            scopes+=("${BASH_REMATCH[1]}")
        fi
    done
    [ "${#scopes[@]}" -gt 0 ] || return 0
    log "stopping the daemons the previous config spawned (the units take over)"
    systemctl --user stop "${scopes[@]}" 2>/dev/null || true
}

# The session environment is imported at login; a running niri keeps the
# one it started with, and its spawns inherit that. ~/.local/bin on the
# compositor's own PATH (read from /proc) is the probe.
session_env_current() {
    local niri_pid
    niri_pid="$(systemctl --user show -p MainPID --value niri.service 2>/dev/null)"
    [ -n "$niri_pid" ] && [ "$niri_pid" != 0 ] || return 0
    tr '\0' '\n' < "/proc/$niri_pid/environ" 2>/dev/null \
        | grep -qE "^PATH=(.*:)?$HOME/\.local/bin(:.*)?$"
}

# ------------------------------------------------------------- 12. summary ---
portals_ok() {
    pacman -Qq xdg-desktop-portal-gtk >/dev/null 2>&1 \
        && pacman -Qq xdg-desktop-portal-gnome >/dev/null 2>&1
}

configs_linked() {
    [ -L "$CFG/niri" ] && [ "$(readlink -f "$CFG/niri")" = "$REPO/config/niri" ]
}

session_units_enabled() {
    # is-enabled over a list is true when any one is; ask one at a time
    local unit
    for unit in "${SESSION_UNITS[@]}"; do
        systemctl --user -q is-enabled "$unit" 2>/dev/null || return 1
    done
}

summary_row() {
    local label="$1" desc="$2"; shift 2
    if "$@" >/dev/null 2>&1; then
        printf '  \033[1;32m[ + ]\033[0m %-14s %s\n' "$label" "$desc"
    else
        printf '  \033[1;31m[ - ]\033[0m %-14s %s\n' "$label" "$desc"
    fi
}

print_summary() {
    printf '\n\033[1m[setup] installed components\033[0m\n'
    summary_row "Niri"          "scrollable-tiling Wayland compositor"   have niri
    summary_row "Dotfiles"      "config/ linked into ~/.config"          configs_linked
    summary_row "Session units" "waybar, mako, wallpaper, idle, cliphist" session_units_enabled
    summary_row "Xwayland-sat." "X11 bridge, auto-spawned by niri"       have xwayland-satellite
    summary_row "Plymouth"      "boot splash (mono theme)"               have plymouthd
    summary_row "Greetd"        "login page (monogreet on niri)"         have monogreet
    summary_row "PipeWire"      "audio server (pulse shim)"              have pipewire
    summary_row "Portals"       "xdg-desktop-portal gtk + gnome"         portals_ok
    summary_row "SSH agent"     "gcr-ssh-agent (gcr-4)"                  test -x /usr/lib/gcr-ssh-agent
    summary_row "Alacritty"     "terminal emulator"                      have alacritty
    summary_row "Rofi"          "application launcher (wayland 2.0)"     have rofi
    summary_row "Waybar"        "status bar"                             have waybar
    summary_row "Mako"          "notification daemon"                    have mako
    summary_row "Swaybg"        "wallpaper daemon"                       have swaybg
    summary_row "Hyprlock"      "screen locker"                          have hyprlock
    summary_row "Swayidle"      "idle manager"                           have swayidle
    summary_row "Yazi"          "terminal file manager (+ ya)"           have yazi
    summary_row "Zellij"        "terminal multiplexer"                   have zellij
    summary_row "Herdr"         "agent workspace manager (herdr.dev)"    have herdr
    summary_row "Cliphist"      "clipboard history"                      have cliphist
    summary_row "Starship"      "shell prompt"                           have starship
    summary_row "Btop"          "system monitor"                         have btop
    summary_row "Micro"         "text editor"                            have micro
    summary_row "Zathura"       "PDF viewer"                             have zathura
    # the imv package ships imv-wayland/imv-x11 plus a wrapper for its
    # desktop file — probe the wayland binary, not a bare `imv`
    summary_row "Imv"           "image viewer"                           have imv-wayland
    summary_row "Mpv"           "media player"                           have mpv
    summary_row "Paru"          "AUR helper (manual installs, updates)"  paru_ok
    summary_row "TLP"           "battery power tuning"                   have tlp
    summary_row "Chafa"         "terminal image renderer (yazi preview)" have chafa
    summary_row "Fzf"           "fuzzy finder"                           have fzf
    summary_row "Zoxide"        "directory jumper"                       have zoxide
    summary_row "Eza"           "ls replacement"                         have eza
    summary_row "Bat"           "cat with highlighting"                  have bat
    summary_row "Fd"            "find replacement"                       have fd
    summary_row "Ripgrep"       "grep replacement (rg)"                  have rg
    summary_row "Delta"         "git diff pager"                         have delta
    summary_row "Checkupdates"  "update probe (bar's updates module)"    have checkupdates
    summary_row "Wl-clipboard"  "Wayland clipboard (wl-copy/wl-paste)"   have wl-copy
    summary_row "Brightnessctl" "backlight control"                      have brightnessctl
    summary_row "Pulsemixer"    "audio mixer popup"                      have pulsemixer
    summary_row "Ksnip"         "screenshot annotator"                   have ksnip
    summary_row "Nerd Font"     "JetBrainsMono Nerd Font"                font_ok
    printf '\n'
}

# ---------------------------------------------------------------- 13. main ---
# The system half needs sudo and a reboot to show; the user half links,
# enables and reloads and is live at once. `install` is both, in order.
system_half() {
    install_packages
    enable_system_units
    install_system_files
    configure_boot
    configure_greeter
}

user_half() {
    # MIME defaults are re-applied on every run: any hand-installed app
    # (a browser most of all) can rewrite mimeapps.list and silently take
    # the PDF and image types with it
    set_default_apps
    configure_git
    link_configs
    install_templates
    enable_units
    install_shell_hooks
    configure_btop
    configure_micro
    apply_desktop_prefs

    niri validate
    log "ALL OK — niri config valid"
    reload_session
}

main() {
    case "${1:-install}" in
        install)
            system_half
            install_paru
            install_herdr
            user_half
            print_summary
            log "wallpaper: put an image at ~/Pictures/wallpaper.jpg (optional)"
            log "reboot: plymouth asks the passphrase, monogreet the login"
            ;;
        system)
            system_half
            print_summary
            log "reboot: plymouth asks the passphrase, monogreet the login"
            ;;
        link|configure)
            user_half
            log "configs are live symlinks — edits apply on save; commit in the repo when happy"
            ;;
        summary)
            print_summary
            ;;
        *)
            die "unknown command: $1 (usage: bash setup.sh [link|system|summary])"
            ;;
    esac
}

# Run only when executed, not when sourced (keeps functions testable).
if [ "${BASH_SOURCE[0]}" = "$0" ]; then
    main "$@"
fi
